//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Markusdrop_wpf.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class company_task
    {
        public company_task()
        {
            this.employee_task = new HashSet<employee_task>();
        }
    
        public int id_task { get; set; }
        public string task_name { get; set; }
        public Nullable<System.DateTime> task_startdate { get; set; }
        public Nullable<System.DateTime> task_enddate { get; set; }
    
        public virtual ICollection<employee_task> employee_task { get; set; }
    }
}
