//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Markusdrop_wpf.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class company_areas
    {
        public company_areas()
        {
            this.users = new HashSet<users>();
        }
    
        public int id_area { get; set; }
        public string area_name { get; set; }
    
        public virtual ICollection<users> users { get; set; }
    }
}
