//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Markusdrop_wpf.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class users
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public users()
        {
            this.employee_task = new HashSet<employee_task>();
        }
    
        public int id_users { get; set; }
        public string first_name { get; set; }
        public string last_name { get; set; }
        public string patronimyc { get; set; }
        public string phone { get; set; }
        public string passport_code { get; set; }
        public string passport_number { get; set; }
        public string INN { get; set; }
        public string SNILS { get; set; }
        public string email { get; set; }
        public Nullable<int> area_id_fk { get; set; }
        public string login { get; set; }
        public string password { get; set; }
        public Nullable<int> user_role_fk { get; set; }
        public byte[] user_image { get; set; }
    
        public virtual company_areas company_areas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<employee_task> employee_task { get; set; }
        public virtual user_role user_role { get; set; }
    }
}
