//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Markusdrop_wpf.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class user_role
    {
        public user_role()
        {
            this.user_auth = new HashSet<user_auth>();
        }
    
        public int id_user_role { get; set; }
        public string user_role_name { get; set; }
    
        public virtual ICollection<user_auth> user_auth { get; set; }
    }
}
