//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Markusdrop_wpf.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class user_auth
    {
        public int id_user_auth { get; set; }
        public Nullable<int> id_user { get; set; }
        public Nullable<int> id_user_role_fk { get; set; }
        public string login { get; set; }
        public string password { get; set; }
    
        public virtual user_role user_role { get; set; }
        public virtual users users { get; set; }
    }
}
