//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Markusdrop_wpf.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class users
    {
        public users()
        {
            this.employee_task = new HashSet<employee_task>();
            this.user_auth = new HashSet<user_auth>();
        }
    
        public int id_users { get; set; }
        public string first_name { get; set; }
        public string last_name { get; set; }
        public string patronimyc { get; set; }
        public string phone { get; set; }
        public string passport_code { get; set; }
        public string passport_number { get; set; }
        public string INN { get; set; }
        public string SNILS { get; set; }
        public string email { get; set; }
        public Nullable<int> area_id_fk { get; set; }
    
        public virtual company_areas company_areas { get; set; }
        public virtual ICollection<employee_task> employee_task { get; set; }
        public virtual ICollection<user_auth> user_auth { get; set; }
    }
}
